# Generated by Django 5.2.7 on 2025-10-01 23:55

from django.db import migrations

from carros.models import Carro


def create_initial_data(apps, schema_editor):
    Carro.objects.create(descricao="Carro A")
    Carro.objects.create(descricao="Carro B")
    Carro.objects.create(descricao="Carro C")
    Carro.objects.create(descricao="Carro D")
    Carro.objects.create(descricao="Carro E")


class Migration(migrations.Migration):
    dependencies = [
        ("carros", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
