# Generated by Django 5.2.7 on 2025-10-02 00:08

from django.db import migrations

from carros.models import Carro


def create_initial_data(apps, schema_editor):
    Carro.objects.create(descricao="Luana")
    Carro.objects.create(descricao="Nathália")
    Carro.objects.create(descricao="Bruno")
    Carro.objects.create(descricao="Robert")
    Carro.objects.create(descricao="Alisson")


class Migration(migrations.Migration):
    dependencies = [
        ("carros", "0002_auto_20251002_0004"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
