# Generated by Django 5.2.7 on 2025-12-03 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carros", "0002_auto_20251002_0002"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corrida",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("local", models.CharField(max_length=100)),
                ("data", models.DateField()),
                (
                    "tamanho_grid",
                    models.IntegerField(
                        help_text="Número máximo de inscrições permitidas para a corrida."
                    ),
                ),
                ("safety_car", models.BooleanField(default=False)),
                ("count_batidas", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Corrida",
                "verbose_name_plural": "Corridas",
                "db_table": "corrida",
            },
        ),
        migrations.CreateModel(
            name="Piloto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("cor_capacete", models.CharField(max_length=50)),
                ("podios", models.IntegerField(default=0)),
                ("vitorias", models.IntegerField(default=0)),
                ("derrotas", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Piloto",
                "verbose_name_plural": "Pilotos",
                "db_table": "piloto",
            },
        ),
        migrations.CreateModel(
            name="InscricaoCorrida",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data_inscricao", models.DateField(auto_now_add=True)),
                ("posicao_largada", models.IntegerField(blank=True, null=True)),
                ("posicao_chegada", models.IntegerField(blank=True, null=True)),
                ("tempo_corrida", models.DurationField(blank=True, null=True)),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carros.carro"
                    ),
                ),
                (
                    "corrida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="carros.corrida",
                    ),
                ),
                (
                    "piloto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carros.piloto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição Corrida",
                "verbose_name_plural": "Inscrições Corrida",
                "db_table": "inscricao_corrida",
            },
        ),
    ]
