# Generated by Django 5.2.7 on 2025-12-03 17:43

from django.apps.registry import Apps
from django.db import migrations

from carros.models import Carro, Corrida, InscricaoCorrida, Piloto


def create_pilotos(apps, schema_editor):
    Piloto.objects.create(
        nome="Ayrton Senna",
        cor_capacete="Amarelo",
        podios=80,
        vitorias=41,
        derrotas=19,
    )
    Piloto.objects.create(
        nome="Max Verstappen",
        cor_capacete="Vermelho e Azul",
        podios=60,
        vitorias=35,
        derrotas=25,
    )
    Piloto.objects.create(
        nome="Michael Schumacher",
        cor_capacete="Vermelho",
        podios=155,
        vitorias=91,
        derrotas=36,
    )
    Piloto.objects.create(
        nome="Lewis Hamilton",
        cor_capacete="Prata",
        podios=182,
        vitorias=103,
        derrotas=45,
    )
    Piloto.objects.create(
        nome="Nigel Mansell",
        cor_capacete="Branco e Vermelho",
        podios=59,
        vitorias=31,
        derrotas=28,
    )
    Piloto.objects.create(
        nome="Jos Verstappen",
        cor_capacete="Azul e Branco",
        podios=1,
        vitorias=0,
        derrotas=10,
    )
    Piloto.objects.create(
        nome="Alain Prost",
        cor_capacete="Branco",
        podios=106,
        vitorias=51,
        derrotas=35,
    )


def create_inscricoes(corrida: Corrida):
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="Lotus 97T"),
        piloto=Piloto.objects.get(nome="Ayrton Senna"),
        posicao_largada=2,
        posicao_chegada=1,
        tempo_corrida="1:30:45",
    )
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="Red Bull RB21"),
        piloto=Piloto.objects.get(nome="Max Verstappen"),
        posicao_largada=19,
        posicao_chegada=2,
        tempo_corrida="1:31:10",
    )
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="Ferrari F2004"),
        piloto=Piloto.objects.get(nome="Michael Schumacher"),
        posicao_largada=1,
        posicao_chegada=3,
        tempo_corrida="1:32:00",
    )
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="Mercedes-AMG F1 W11"),
        piloto=Piloto.objects.get(nome="Lewis Hamilton"),
        posicao_largada=3,
        posicao_chegada=4,
        tempo_corrida="1:32:30",
    )
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="Williams FW14B"),
        piloto=Piloto.objects.get(nome="Nigel Mansell"),
        posicao_largada=4,
        posicao_chegada=5,
        tempo_corrida="1:33:00",
    )
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="Benetton B194"),
        piloto=Piloto.objects.get(nome="Jos Verstappen"),
        posicao_largada=15,
        posicao_chegada=6,
        tempo_corrida="1:34:00",
    )
    InscricaoCorrida.objects.create(
        corrida=corrida,
        carro=Carro.objects.get(descricao="McLaren MP4/4"),
        piloto=Piloto.objects.get(nome="Alain Prost"),
        posicao_largada=5,
        posicao_chegada=7,
        tempo_corrida="1:34:30",
    )


def create_corridas(apps: Apps, schema_editor):
    corrida1 = Corrida.objects.create(
        local="Monza",
        data="2025-09-14",
        tamanho_grid=20,
        safety_car=True,
        count_batidas=2,
    )

    corrida2 = Corrida.objects.create(
        local="Silverstone",
        data="2025-10-05",
        tamanho_grid=20,
        safety_car=False,
        count_batidas=0,
    )

    corrida3 = Corrida.objects.create(
        local="Spa-Francorchamps",
        data="2025-08-24",
        tamanho_grid=20,
        safety_car=True,
        count_batidas=3,
    )

    corrida4 = Corrida.objects.create(
        local="Suzuka",
        data="2025-10-19",
        tamanho_grid=20,
        safety_car=False,
        count_batidas=1,
    )

    corrida5 = Corrida.objects.create(
        local="Interlagos",
        data="2025-11-02",
        tamanho_grid=20,
        safety_car=True,
        count_batidas=4,
    )

    corrida6 = Corrida.objects.create(
        local="Cingapura",
        data="2025-09-21",
        tamanho_grid=20,
        safety_car=False,
        count_batidas=0,
    )

    corrida7 = Corrida.objects.create(
        local="Mônaco",
        data="2025-05-25",
        tamanho_grid=20,
        safety_car=True,
        count_batidas=5,
    )

    create_inscricoes(corrida1)
    create_inscricoes(corrida2)
    create_inscricoes(corrida3)
    create_inscricoes(corrida4)
    create_inscricoes(corrida5)
    create_inscricoes(corrida6)
    create_inscricoes(corrida7)


class Migration(migrations.Migration):
    dependencies = [
        ("carros", "0003_corrida_piloto_inscricaocorrida"),
    ]

    operations = [
        migrations.RunPython(create_pilotos),
        migrations.RunPython(create_corridas),
    ]
