# Generated by Django 5.2.7 on 2025-12-03 21:07

from django.db import migrations

from carros.models import Piloto


def create_rookies(apps, schema_editor):
    Piloto.objects.create(
        nome="Gabriel Bortolotto",
        cor_capacete="Verde e Amarelo",
        podios=10,
        vitorias=5,
        derrotas=5,
    )
    Piloto.objects.create(
        nome="kimi Antonelli",
        cor_capacete="Vermelho e Branco",
        podios=8,
        vitorias=3,
        derrotas=5,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("carros", "0004_auto_20251203_1940"),
    ]

    operations = [
        migrations.RunPython(create_rookies),
    ]
