# Generated by Django 5.2.7 on 2025-12-03 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_auto_20251203_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'db_table': 'campeonato',
            },
        ),
        migrations.AddField(
            model_name='corrida',
            name='campeonato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='carros.campeonato'),
        ),
    ]
